services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ecotask-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: file:./dev.db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_data:/app/prisma
    networks:
      - ecotask-network
    command: npm run dev

  # Frontend React/Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecotask-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ecotask-network

volumes:
  backend_data:

networks:
  ecotask-network:
    driver: bridge
