services:
  backend:
    image: registry.gitlab.com/virgile_eratel/ecotask/backend:latest
    container_name: ecotask-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: file:./data/prod.db
      JWT_SECRET: test
      PORT: 3002
      FRONTEND_URL: http://51.68.233.128
      DOMAIN: 51.68.233.128
    volumes:
      - backend_data:/app/data
    networks:
      - ecotask-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: registry.gitlab.com/virgile_eratel/ecotask/frontend:latest
    container_name: ecotask-frontend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecotask-network

volumes:
  backend_data:

networks:
  ecotask-network:
    driver: bridge